/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/color/': RouteRecordInfo<
      '/color/',
      '/color',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/format/': RouteRecordInfo<
      '/format/',
      '/format',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/format/components/JsonNode': RouteRecordInfo<
      '/format/components/JsonNode',
      '/format/components/JsonNode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/har/': RouteRecordInfo<
      '/har/',
      '/har',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hi/[name]': RouteRecordInfo<
      '/hi/[name]',
      '/hi/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/money/': RouteRecordInfo<
      '/money/',
      '/money',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/time/': RouteRecordInfo<
      '/time/',
      '/time',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/whiteboard/': RouteRecordInfo<
      '/whiteboard/',
      '/whiteboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/color/index.vue': {
      routes:
        | '/color/'
      views:
        | never
    }
    'src/pages/format/index.vue': {
      routes:
        | '/format/'
      views:
        | never
    }
    'src/pages/format/components/JsonNode.vue': {
      routes:
        | '/format/components/JsonNode'
      views:
        | never
    }
    'src/pages/har/index.vue': {
      routes:
        | '/har/'
      views:
        | never
    }
    'src/pages/hi/[name].vue': {
      routes:
        | '/hi/[name]'
      views:
        | never
    }
    'src/pages/money/index.vue': {
      routes:
        | '/money/'
      views:
        | never
    }
    'src/pages/time/index.vue': {
      routes:
        | '/time/'
      views:
        | never
    }
    'src/pages/whiteboard/index.vue': {
      routes:
        | '/whiteboard/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
